import { React, Head, useState, useEffect } from '@shared/vendor';
import { NextPage } from '@shared/vendorTypes';
import { MetabaseAppEmbed, SearchBox } from "@shared/components/presentational";
import { useRouter } from 'next/router'
interface User {
  id: string;
}

// const useInnerHeight = () => {
//   const [innerHeight, setInnerHeight] = useState(window?.innerHeight);
//   useEffect(() => {
//     const onResize = () => setInnerHeight(window?.innerHeight);
//     window.addEventListener("resize", onResize);
//     return () => window.removeEventListener("resize", onResize);
//   }, []);
//   return innerHeight;
// }

const Home: NextPage = () => {
  const [user, setUser] = useState<User>({ id: "1" });
  const [tokenAddress, setTokenAddress] = useState("");
  // const innerHeight = useInnerHeight();
  const router = useRouter()

  const config = {
    METABASE_URL: "https://enum.metabaseapp.com",
    // AUTH_BASE_URL: "http://localhost:8080/",
    AUTH_BASE_URL:
      "https://us-central1-cosmic-descent-339520.cloudfunctions.net/metabase-prototype-login",
  };

  const getAppPath = (location: any) => {
    return `/analytics/dashboard/5-use-case-1?token_address=${tokenAddress}`;
  };

  return (
    <div>
      <Head>
        <title>Definitive | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <h1>Home Page</h1>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum, iure adipisci magnam expedita soluta vitae fuga
          ab mollitia praesentium dolorem cumque molestias libero quaerat ad omnis in voluptates porro aliquid?
        </p>
        <SearchBox
          placeholder="Token Address"
          onChange={setTokenAddress}
          onSubmit={() => {}}
        ></SearchBox>
        <MetabaseAppEmbed
          base={config.METABASE_URL}
          // path={getAppPath(router.location).replace(/\/analytics/, "")}
          path="/dashboard/5-use-case-1?token_address="
          className={"h-full"}
          onLocationChange={(location: any) => {
            // router.push(
            //   `/analytics${getAppPath(location).replace(/^\/$/, "")}`
            // );
          }}
          getAuthUrl={() =>
            `${config.AUTH_BASE_URL}?user=${user.id}&return_to=https%3A%2F%2Fenum.metabaseapp.com%2Fdashboard%2F5-use-case-1`
          }
          fitHeight={1000 - 56}
          onMessage={undefined}
          onFrameChange={undefined}
        />
      </main>
    </div>
  );
}

export default Home;
