import { React, Head } from '@shared/vendor';
import { NextPage } from '@shared/vendorTypes';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Definitive | Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>

    <main>
      <h1>Home Page</h1>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum, iure adipisci magnam expedita soluta vitae fuga
        ab mollitia praesentium dolorem cumque molestias libero quaerat ad omnis in voluptates porro aliquid?
      </p>
    </main>
  </div>
);

export default Home;
